### PR TITLE
Update Repo URL

### PR DESCRIPTION
**Pull request by giswqs**
This PR updates all the repo url from giswqs to opengeos. If you cloned the repo previously, it is recommended that you update the Git repo remote URL as follows.

```bash
git remote set-url origin https://github.com/opengeos/whiteboxR.git
```

### CODE REVIEW

**Comment by giswqs** [comment]
Yes, I need to update the repo URL.

**Comment by brownag** [comment]
Sorry, looks like it was my doing after all, should have looked closer earlier. 

I had set the workflow up so it wouldn't run on my fork brownag/whiteboxR... so that line also needed update of the repo owner to "opengeos"

**Comment by brownag** [comment]
@giswqs The docker-publish.yml action now runs as it should, but fails to upload. It may be looking for secrets for dockerhub or similar?

See recent run e.g. https://github.com/opengeos/whiteboxR/actions/runs/5651766769

**Comment by brownag** [comment]
Yes, probably! Then will also need to correct the README. 

Should it also be `ghcr.io/giswqs/whiteboxR` for https://github.com/users/giswqs/packages/container/package/whiteboxr? I can't tell from the error if both uploads fail, or just the dockerhub is failing and it just hasn't got to creating ghcr.io/opengeos/whiteboxR

**Comment by giswqs** [comment]
Yeah, it is a bit confusion after moving the repo to the opengeos GitHub organization.

For GitHub registry, it should be `ghcr.io/opengeos/whiteboxR`

For Docker Hub, it should be `giswqs/whiteboxR`. Docker Hub is no longer free for organizations, and that's why it is still under my personal account.

**Comment by brownag** [comment]
Ok got it! And that makes sense about the organization account. 

I made correction in the YAML file so it should works as you describe: https://github.com/opengeos/whiteboxR/actions/runs/5652062082/job/15311122226
Glad it was a simple fix :)

It is worth making this container and keeping it up to date at least with the CRAN package releases, lots of folks use Docker. Thanks!!

**Comment by giswqs** [comment]
Great! Thank you for fixing it. I can confirm that both have been updated properly. 

https://github.com/opengeos/whiteboxR/pkgs/container/whiteboxr

https://hub.docker.com/r/giswqs/whiteboxr

**Pull request merged**
